server:
  port: 8080
spring:
  application:
    name: music
  datasource:
    url: jdbc:mysql://localhost:3306/music_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info
    com.music: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
